version: '2'

services:
  app:
    build: .
    command: bash -c "mvn clean install; java -jar target/lead-0.0.1-SNAPSHOT.jar"
    volumes:
      - .:/var/www
      - ~/.m2:/root/.m2
    ports:
      - 8080:8080
    depends_on:
    - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raiden
      MYSQL_USER: root
      MYSQL_PASSWORD: root
